### ISSUE TITLE
Example code broken

### ISSUE THREAD

**Issue by teixeirazeus** [lewiseman/easy_dashboard#6]
Hello,
I believe the example code is broken.
In one of the last commits https://github.com/lewiseman/easy_dashboard/commit/81d51e9c0a411e8c5971096312d6979b28d9508f , some changes were added.

example/lib/main.dart
`EasyAppController` to `EasyController`.
But EasyController is not define. I believe they are the same classes. It was just a name refactoring.

example/lib/flat_example/flat.dart
`Easy.flat` is not define.  I couldn't find it in the code.

**Comment by lewiseman** [comment]
Yeah this is true , sorry for that , i will try and fix it this week @teixeirazeus

**Comment by lewiseman** [comment]
i have merged the pull request
